# Demo config file for Limesurf
# www.biophysics.fr
meshes:
    deflated:
        source: demo.ply
        type: 1
        # 1: elastic 
        power_law: 2
        prestrain: 1.0
        k_elast: 1.0

runs:
    1:
        duration: 500
        n_frames: 5
        dt: 0.005

        pressure: 0.0
        confinement:
            y:  
                min: -2.2
                max:  2.2
                stiffness: 40
            z:  
                min: -1.6
                max:  1.6
                stiffness: 40
    2:
        pressure: 1.0
    3:
        pressure: 0.0
